Document: keimpx
Title: Debian keimpx Manual
Author: <insert document author here>
Abstract: This manual describes what keimpx is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/keimpx/keimpx.sgml.gz

Format: postscript
Files: /usr/share/doc/keimpx/keimpx.ps.gz

Format: text
Files: /usr/share/doc/keimpx/keimpx.text.gz

Format: HTML
Index: /usr/share/doc/keimpx/html/index.html
Files: /usr/share/doc/keimpx/html/*.html
